services:
  apache:
    profiles:
      - apache
    image: httpd:alpine
    ports:
      - "80:80"
    command: /bin/sh -c "echo 'Include /usr/local/apache2/conf/apache.vhost.conf' >> /usr/local/apache2/conf/httpd.conf && httpd -D FOREGROUND"
    volumes:
      - ./conf/apache.vhost.conf:/usr/local/apache2/conf/apache.vhost.conf
      - "${WEB_ROOT_DIR:-${HOME}/zabbix}:/var/www/html"
    networks:
      - internal

  nginx:
    profiles:
      - nginx
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - "${WEB_ROOT_DIR:-${HOME}/zabbix}:/var/www/html"
    networks:
      - internal


  phpfpm56:
    hostname: php
    profiles:
      - phpfpm56
    build:
      context: .
      dockerfile: ./Dockerfile/php5.6.Dockerfile
    image: zabbix-php:5.6
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - "${WEB_ROOT_DIR:-${HOME}/zabbix}:/var/www/html"
      - "${LOG_ROOT_DIR:-${HOME}/zabbix/log}:/var/log"
    networks:
      - internal

  phpfpm74:
    hostname: php
    profiles:
      - phpfpm74
    build:
      context: .
      dockerfile: ./Dockerfile/php7.4.Dockerfile
    image: zabbix-php:7.4
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - "${WEB_ROOT_DIR:-${HOME}/zabbix}:/var/www/html"
      - "${LOG_ROOT_DIR:-${HOME}/zabbix/log}:/var/log"
    networks:
      - internal

  phpfpm80:
    hostname: php
    profiles:
      - phpfpm80
    build:
      context: .
      dockerfile: ./Dockerfile/php8.0.Dockerfile
    image: zabbix-php:8.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - "${WEB_ROOT_DIR:-${HOME}/zabbix}:/var/www/html"
      - "${LOG_ROOT_DIR:-${HOME}/zabbix/log}:/var/log"
    networks:
      - internal

  phpfpm83:
    hostname: php
    profiles:
      - phpfpm83
    build:
      context: .
      dockerfile: ./Dockerfile/php8.3.Dockerfile
    image: zabbix-php:8.3
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - "${WEB_ROOT_DIR:-${HOME}/zabbix}:/var/www/html"
      - "${LOG_ROOT_DIR:-${HOME}/zabbix/log}:/var/log"
    networks:
      - internal


  mariadb:
    hostname: db
    profiles:
      - mariadb
    image: mariadb:lts
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - "${VOLUME_ROOT_DIR:-./docker-volume}/mariadb:/var/lib/mysql"
    networks:
      - internal

  mysql:
    hostname: db
    profiles:
      - mysql
    image: mysql:8.2
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "${VOLUME_ROOT_DIR:-./docker-volume}/mysql:/var/lib/mysql"
    networks:
      - internal

  mysql-legacy:
    hostname: db
    profiles:
      - mysql-legacy
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "${VOLUME_ROOT_DIR:-./docker-volume}/mysql-legacy:/var/lib/mysql"
    networks:
      - internal

networks:
  internal:
    driver: bridge
